# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/TELECO/4o/1er semestre/DSED/proyecto final/controlador final bueno, entrega/controladorV2/controladorV2.srcs/Nexys4DDR_Master.xdc

# IP: new/MemoriaRAM/MemoriaRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MemoriaRAM || ORIG_REF_NAME==MemoriaRAM}]

# IP: new/clk_12Megas/clk_12Megas.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_12Megas || ORIG_REF_NAME==clk_12Megas}]
